### ISSUE TITLE
Lazy loading with suspense

### ISSUE THREAD

**Issue by niharikasingh** [Daydreamer-riri/vite-react-ssg#29]
Thanks so much for creating this library :) 

I was trying to set up lazy loading in a project, and I had to use `Suspense` to get the lazy-loaded component to appear properly. The code ended up looking like: 

```jsx
import { Suspense, lazy } from 'react';
import { ViteReactSSG } from 'vite-react-ssg'

const Page1Component = lazy(() => import('./Page1Component.jsx'));
const Page2Component = lazy(() => import('./Page2Component.jsx'));

const routes = [
  {
    path: '/page1',
    element: <Suspense fallback={<div/>}><Page1Component /></Suspense>,
  },
  {
    path: '/page2',
    element: <Suspense fallback={<div/>}><Page2Component /></Suspense>,
  },
]

export const createRoot = ViteReactSSG(
  // react-router-dom data routes
  { routes },
  // function to have custom setups
  () => {},
)
```

Do you think this is worth adding to `README.md`? Happy to create a PR if so.

**Comment by Daydreamer-riri** [comment]
Hi @niharikasingh, thank you so much for the favorites!

Regarding delayed loading, I think the recommended way of delayed loading for `vite-react-ssg` (including its upstream `react-router`) should be to use the `lazy` field: https://github.com/Daydreamer-riri/vite-react-ssg#lazy

```tsx
import React from 'react'
import type { RouteRecord } from 'vite-react-ssg'
import './App.css'

const Layout = React.lazy(() => import('./Layout'))

export const routes: RouteRecord[] = [
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        path: 'a',
        lazy: () => import('./pages/a'),
      },
      {
        index: true,
        lazy: () => defaultToComponent(import('./pages/index')),
      },
      {
        path: 'nest/:b',
        lazy: () => defaultToComponent(import('./pages/nest/[b]')),
      },
    ],
  },
]

async function defaultToComponent(routePromise: Promise<RouteRecord & { default: any }>) {
  const routeModule = await routePromise

  return { ...routeModule, Component: routeModule.default }
}
```

Layout:
```tsx
import { Suspense, useState } from 'react'
import { Outlet } from 'react-router-dom'
import { Head } from 'vite-react-ssg'
import './layout.css'

export default function Layout() {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/react.svg" />
        <body className={`body-class-in-head`} />
      </Head>
      <main>
        <h1 className="layout">Layout</h1>
        <Suspense>
          <Outlet />
        </Suspense>
      </main>
    </>
  )
}
```

This allows lazy loading of components, loaders, and other routing-related resources.

Also if you introduce css files in your lazy loaded component (eg: `import 'styles.css'`), the only way to not cause a FOUC is to use the `lazy` field, since I get the corresponding entry file for that route by parsing the string passed to the function in the `lazy` field(see: https://github.com/Daydreamer-riri/vite-react-ssg/blob/main/src/node/assets.ts#L43-L46https://github.com/Daydreamer-riri/vite-react-ssg/blob/main/src/node/assets.ts#L43-L46).

Finally, if you think the documentation on `lazy` is too brief (and I personally think it is), feel free to submit a PR!
