### ISSUE TITLE
Improve development functions

### ISSUE THREAD

**Issue by Daydreamer-riri** [Daydreamer-riri/vite-react-ssg#8]
Link: #7.

- [x] support port arg
- [x] automatic redirect

**Comment by childrentime** [comment]
support auto retry available port😎

**Comment by Daydreamer-riri** [comment]
> support auto retry available port😎

Good idea 💡

**Comment by Daydreamer-riri** [comment]
@CondorHero, Can you provide more suggestions?

**Comment by condorheroblog** [comment]
https://github.com/Daydreamer-riri/vite-react-ssg#use-csr-during-development

I see that the development environment already supports not replacing my Vite commands. It retains the development experience of vite and can also use vite-react-ssg. This is great.

The problem of development experience has been solved, and I have no other particularly strong needs.

For the vite-react-ssg command, I think it is basically consistent with [Vite Cli](https://vitejs.dev/guide/cli.html#vite). But it’s okay not to do this, because users should use it less.

Wish you have a nice day.

**Comment by condorheroblog** [comment]
Encountered an experience problem. Use `vite-react-ssg dev` to start the service and change the contents of the `index.html` file. The hot update fails. Even if the browser is refreshed manually, the changed HTML will not be reloaded.

**Comment by Daydreamer-riri** [comment]
Close with [e399bc3](https://github.com/Daydreamer-riri/vite-react-ssg/commit/e399bc328d87b987ef2b84e32af01f55311eb002).
